
# Provide one entry in input for each desired analysis.
# The value on the left of the colon gives the label used for the analysis.
# The value on the right gives the study description file.

#   The MVMR pipeline will run MVMR treating the first trait in the study description file
#   as the outcome and the other traits as exposures.
#   You can choose from four MVMR methods in the analysis section.
input:
       example1: 'snakemake-pipeline/example_csv1.csv'
       example1: 'snakemake-pipeline/example_csv2.csv'

analysis:
    # LD pruning options:
    # r2_thresh: threshold for pairwise r^2 between variants
    # clump_kb: Maximum distance for pruning.
    # ref_path: Path to plink format reference data (.bim .bed .fam)
    # ld_prioritization: either pvalue or rank, maybe eventually sd
    ldprune:
        r2_thresh: 0.01 # list ok
        clump_kb: 1000 # list ok
        ld_prioritization: ["pvalue"] # list ok,  "pvalue" or "rank"
        ref_path: "1kg_plink/EUR"
    R:
      type: "pt" # options are "pt", "ldsc", "none"
      pthresh: [0.05]
      l2_dir: "eur_w_ld_chr/" # not a list
      cond_num: 1e3
   # MVMR options.
   # Set run to True for the methods you want to run and False for the methods you don't want to run.
   # Sub-sections provide options for each method, mostly self-explanatory.
   # af_thresh: Allele frequency threshold
    mvmr:
      af_thresh: 0
      esmr:
        run: False
        p_thresh: [5e-08]
        max_iter: 100
      grapple:
        run: True
        p_thresh: [1e-5]
        max_iter: 1e6
      bee:
        run: False
        p_thresh: [5e-8]
        pleio_pt: [0, 0.05]
        max_iter: 100
      ivw:
        run: False
        p_thresh: [5e-8]

out:
    # Output data options: Remember to leave a slash at the end!
    # data_dir: Directory to store reformatted data
    # output_dir: Where to store results
    data_dir: "mvmr_data/"
    output_dir: "mvmr_results/"
